# Generated by Django 2.2 on 2020-05-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
