# Generated by Django 2.2 on 2020-05-17 11:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20200517_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='images/category', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, default=16, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.Category', verbose_name='Категория'),
        ),
    ]
