# Generated by Django 2.2 on 2020-05-17 11:28

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200517_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(default=16, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.Category', verbose_name='Категория'),
        ),
    ]
