# Generated by Django 2.2 on 2020-05-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, upload_to='images/product_preview', verbose_name='Превью'),
        ),
    ]
