# Generated by Django 2.2 on 2020-05-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20200518_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_product',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество'),
        ),
    ]
