# Generated by Django 2.2 on 2020-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_product_count_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
